// Generated by gencpp from file simtech_driver/SrvRobotCommand.msg
// DO NOT EDIT!


#ifndef SIMTECH_DRIVER_MESSAGE_SRVROBOTCOMMAND_H
#define SIMTECH_DRIVER_MESSAGE_SRVROBOTCOMMAND_H

#include <ros/service_traits.h>


#include <simtech_driver/SrvRobotCommandRequest.h>
#include <simtech_driver/SrvRobotCommandResponse.h>


namespace simtech_driver
{

struct SrvRobotCommand
{

typedef SrvRobotCommandRequest Request;
typedef SrvRobotCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvRobotCommand
} // namespace simtech_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simtech_driver::SrvRobotCommand > {
  static const char* value()
  {
    return "22c7c465d64c7e74c6ae22029c7ca150";
  }

  static const char* value(const ::simtech_driver::SrvRobotCommand&) { return value(); }
};

template<>
struct DataType< ::simtech_driver::SrvRobotCommand > {
  static const char* value()
  {
    return "simtech_driver/SrvRobotCommand";
  }

  static const char* value(const ::simtech_driver::SrvRobotCommand&) { return value(); }
};


// service_traits::MD5Sum< ::simtech_driver::SrvRobotCommandRequest> should match
// service_traits::MD5Sum< ::simtech_driver::SrvRobotCommand >
template<>
struct MD5Sum< ::simtech_driver::SrvRobotCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simtech_driver::SrvRobotCommand >::value();
  }
  static const char* value(const ::simtech_driver::SrvRobotCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simtech_driver::SrvRobotCommandRequest> should match
// service_traits::DataType< ::simtech_driver::SrvRobotCommand >
template<>
struct DataType< ::simtech_driver::SrvRobotCommandRequest>
{
  static const char* value()
  {
    return DataType< ::simtech_driver::SrvRobotCommand >::value();
  }
  static const char* value(const ::simtech_driver::SrvRobotCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simtech_driver::SrvRobotCommandResponse> should match
// service_traits::MD5Sum< ::simtech_driver::SrvRobotCommand >
template<>
struct MD5Sum< ::simtech_driver::SrvRobotCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simtech_driver::SrvRobotCommand >::value();
  }
  static const char* value(const ::simtech_driver::SrvRobotCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simtech_driver::SrvRobotCommandResponse> should match
// service_traits::DataType< ::simtech_driver::SrvRobotCommand >
template<>
struct DataType< ::simtech_driver::SrvRobotCommandResponse>
{
  static const char* value()
  {
    return DataType< ::simtech_driver::SrvRobotCommand >::value();
  }
  static const char* value(const ::simtech_driver::SrvRobotCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMTECH_DRIVER_MESSAGE_SRVROBOTCOMMAND_H
