// Generated by gencpp from file simtech_robot_laser_control/MsgSetpoint.msg
// DO NOT EDIT!


#ifndef SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGSETPOINT_H
#define SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGSETPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simtech_robot_laser_control
{
template <class ContainerAllocator>
struct MsgSetpoint_
{
  typedef MsgSetpoint_<ContainerAllocator> Type;

  MsgSetpoint_()
    : setpoint(0.0)  {
    }
  MsgSetpoint_(const ContainerAllocator& _alloc)
    : setpoint(0.0)  {
  (void)_alloc;
    }



   typedef float _setpoint_type;
  _setpoint_type setpoint;





  typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> const> ConstPtr;

}; // struct MsgSetpoint_

typedef ::simtech_robot_laser_control::MsgSetpoint_<std::allocator<void> > MsgSetpoint;

typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgSetpoint > MsgSetpointPtr;
typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgSetpoint const> MsgSetpointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator1> & lhs, const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator2> & rhs)
{
  return lhs.setpoint == rhs.setpoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator1> & lhs, const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simtech_robot_laser_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4b0a2d45139da8ec935e105dc5a9cb2";
  }

  static const char* value(const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4b0a2d45139da8eULL;
  static const uint64_t static_value2 = 0xc935e105dc5a9cb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtech_robot_laser_control/MsgSetpoint";
  }

  static const char* value(const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 setpoint\n"
;
  }

  static const char* value(const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgSetpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtech_robot_laser_control::MsgSetpoint_<ContainerAllocator>& v)
  {
    s << indent << "setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.setpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGSETPOINT_H
