// Generated by gencpp from file simtech_robot_laser_control/SrvRobotCommandRequest.msg
// DO NOT EDIT!


#ifndef SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_SRVROBOTCOMMANDREQUEST_H
#define SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_SRVROBOTCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simtech_robot_laser_control
{
template <class ContainerAllocator>
struct SrvRobotCommandRequest_
{
  typedef SrvRobotCommandRequest_<ContainerAllocator> Type;

  SrvRobotCommandRequest_()
    : command()  {
    }
  SrvRobotCommandRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SrvRobotCommandRequest_

typedef ::simtech_robot_laser_control::SrvRobotCommandRequest_<std::allocator<void> > SrvRobotCommandRequest;

typedef boost::shared_ptr< ::simtech_robot_laser_control::SrvRobotCommandRequest > SrvRobotCommandRequestPtr;
typedef boost::shared_ptr< ::simtech_robot_laser_control::SrvRobotCommandRequest const> SrvRobotCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator1> & lhs, const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator1> & lhs, const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simtech_robot_laser_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtech_robot_laser_control/SrvRobotCommandRequest";
  }

  static const char* value(const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvRobotCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtech_robot_laser_control::SrvRobotCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_SRVROBOTCOMMANDREQUEST_H
