(cl:defpackage simtech_driver-srv
  (:use )
  (:export
   "SRVROBOTCOMMAND"
   "<SRVROBOTCOMMAND-REQUEST>"
   "SRVROBOTCOMMAND-REQUEST"
   "<SRVROBOTCOMMAND-RESPONSE>"
   "SRVROBOTCOMMAND-RESPONSE"
  ))

