// Generated by gencpp from file simtech_kuka_rsi_hw_interface/MsgCartPosition.msg
// DO NOT EDIT!


#ifndef SIMTECH_KUKA_RSI_HW_INTERFACE_MESSAGE_MSGCARTPOSITION_H
#define SIMTECH_KUKA_RSI_HW_INTERFACE_MESSAGE_MSGCARTPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace simtech_kuka_rsi_hw_interface
{
template <class ContainerAllocator>
struct MsgCartPosition_
{
  typedef MsgCartPosition_<ContainerAllocator> Type;

  MsgCartPosition_()
    : header()
    , X(0.0)
    , Y(0.0)
    , Z(0.0)
    , A(0.0)
    , B(0.0)
    , C(0.0)  {
    }
  MsgCartPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , X(0.0)
    , Y(0.0)
    , Z(0.0)
    , A(0.0)
    , B(0.0)
    , C(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _X_type;
  _X_type X;

   typedef float _Y_type;
  _Y_type Y;

   typedef float _Z_type;
  _Z_type Z;

   typedef float _A_type;
  _A_type A;

   typedef float _B_type;
  _B_type B;

   typedef float _C_type;
  _C_type C;





  typedef boost::shared_ptr< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> const> ConstPtr;

}; // struct MsgCartPosition_

typedef ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<std::allocator<void> > MsgCartPosition;

typedef boost::shared_ptr< ::simtech_kuka_rsi_hw_interface::MsgCartPosition > MsgCartPositionPtr;
typedef boost::shared_ptr< ::simtech_kuka_rsi_hw_interface::MsgCartPosition const> MsgCartPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator1> & lhs, const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.X == rhs.X &&
    lhs.Y == rhs.Y &&
    lhs.Z == rhs.Z &&
    lhs.A == rhs.A &&
    lhs.B == rhs.B &&
    lhs.C == rhs.C;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator1> & lhs, const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simtech_kuka_rsi_hw_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b9231b9f3527787d1bed1c5f318565f";
  }

  static const char* value(const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b9231b9f3527787ULL;
  static const uint64_t static_value2 = 0xd1bed1c5f318565fULL;
};

template<class ContainerAllocator>
struct DataType< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtech_kuka_rsi_hw_interface/MsgCartPosition";
  }

  static const char* value(const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 X\n"
"float32 Y\n"
"float32 Z\n"
"float32 A\n"
"float32 B\n"
"float32 C\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.Z);
      stream.next(m.A);
      stream.next(m.B);
      stream.next(m.C);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgCartPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtech_kuka_rsi_hw_interface::MsgCartPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<float>::stream(s, indent + "  ", v.Z);
    s << indent << "A: ";
    Printer<float>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<float>::stream(s, indent + "  ", v.B);
    s << indent << "C: ";
    Printer<float>::stream(s, indent + "  ", v.C);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTECH_KUKA_RSI_HW_INTERFACE_MESSAGE_MSGCARTPOSITION_H
