// Generated by gencpp from file simtech_kuka_rsi_hw_interface/MsgCartVelocity.msg
// DO NOT EDIT!


#ifndef SIMTECH_KUKA_RSI_HW_INTERFACE_MESSAGE_MSGCARTVELOCITY_H
#define SIMTECH_KUKA_RSI_HW_INTERFACE_MESSAGE_MSGCARTVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace simtech_kuka_rsi_hw_interface
{
template <class ContainerAllocator>
struct MsgCartVelocity_
{
  typedef MsgCartVelocity_<ContainerAllocator> Type;

  MsgCartVelocity_()
    : header()
    , Vx(0.0)
    , Vy(0.0)
    , Vz(0.0)
    , Speed(0.0)  {
    }
  MsgCartVelocity_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Vx(0.0)
    , Vy(0.0)
    , Vz(0.0)
    , Speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _Vx_type;
  _Vx_type Vx;

   typedef float _Vy_type;
  _Vy_type Vy;

   typedef float _Vz_type;
  _Vz_type Vz;

   typedef float _Speed_type;
  _Speed_type Speed;





  typedef boost::shared_ptr< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct MsgCartVelocity_

typedef ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<std::allocator<void> > MsgCartVelocity;

typedef boost::shared_ptr< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity > MsgCartVelocityPtr;
typedef boost::shared_ptr< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity const> MsgCartVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator1> & lhs, const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Vx == rhs.Vx &&
    lhs.Vy == rhs.Vy &&
    lhs.Vz == rhs.Vz &&
    lhs.Speed == rhs.Speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator1> & lhs, const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simtech_kuka_rsi_hw_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "595faad6b795bb4eb50cefc150fb1610";
  }

  static const char* value(const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x595faad6b795bb4eULL;
  static const uint64_t static_value2 = 0xb50cefc150fb1610ULL;
};

template<class ContainerAllocator>
struct DataType< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtech_kuka_rsi_hw_interface/MsgCartVelocity";
  }

  static const char* value(const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 Vx\n"
"float32 Vy\n"
"float32 Vz\n"
"float32 Speed\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Vx);
      stream.next(m.Vy);
      stream.next(m.Vz);
      stream.next(m.Speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgCartVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtech_kuka_rsi_hw_interface::MsgCartVelocity_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Vx: ";
    Printer<float>::stream(s, indent + "  ", v.Vx);
    s << indent << "Vy: ";
    Printer<float>::stream(s, indent + "  ", v.Vy);
    s << indent << "Vz: ";
    Printer<float>::stream(s, indent + "  ", v.Vz);
    s << indent << "Speed: ";
    Printer<float>::stream(s, indent + "  ", v.Speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTECH_KUKA_RSI_HW_INTERFACE_MESSAGE_MSGCARTVELOCITY_H
