// Generated by gencpp from file motion_planning_kuka/SrvRobotCommand.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNING_KUKA_MESSAGE_SRVROBOTCOMMAND_H
#define MOTION_PLANNING_KUKA_MESSAGE_SRVROBOTCOMMAND_H

#include <ros/service_traits.h>


#include <motion_planning_kuka/SrvRobotCommandRequest.h>
#include <motion_planning_kuka/SrvRobotCommandResponse.h>


namespace motion_planning_kuka
{

struct SrvRobotCommand
{

typedef SrvRobotCommandRequest Request;
typedef SrvRobotCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvRobotCommand
} // namespace motion_planning_kuka


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_planning_kuka::SrvRobotCommand > {
  static const char* value()
  {
    return "22c7c465d64c7e74c6ae22029c7ca150";
  }

  static const char* value(const ::motion_planning_kuka::SrvRobotCommand&) { return value(); }
};

template<>
struct DataType< ::motion_planning_kuka::SrvRobotCommand > {
  static const char* value()
  {
    return "motion_planning_kuka/SrvRobotCommand";
  }

  static const char* value(const ::motion_planning_kuka::SrvRobotCommand&) { return value(); }
};


// service_traits::MD5Sum< ::motion_planning_kuka::SrvRobotCommandRequest> should match
// service_traits::MD5Sum< ::motion_planning_kuka::SrvRobotCommand >
template<>
struct MD5Sum< ::motion_planning_kuka::SrvRobotCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_planning_kuka::SrvRobotCommand >::value();
  }
  static const char* value(const ::motion_planning_kuka::SrvRobotCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_planning_kuka::SrvRobotCommandRequest> should match
// service_traits::DataType< ::motion_planning_kuka::SrvRobotCommand >
template<>
struct DataType< ::motion_planning_kuka::SrvRobotCommandRequest>
{
  static const char* value()
  {
    return DataType< ::motion_planning_kuka::SrvRobotCommand >::value();
  }
  static const char* value(const ::motion_planning_kuka::SrvRobotCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_planning_kuka::SrvRobotCommandResponse> should match
// service_traits::MD5Sum< ::motion_planning_kuka::SrvRobotCommand >
template<>
struct MD5Sum< ::motion_planning_kuka::SrvRobotCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_planning_kuka::SrvRobotCommand >::value();
  }
  static const char* value(const ::motion_planning_kuka::SrvRobotCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_planning_kuka::SrvRobotCommandResponse> should match
// service_traits::DataType< ::motion_planning_kuka::SrvRobotCommand >
template<>
struct DataType< ::motion_planning_kuka::SrvRobotCommandResponse>
{
  static const char* value()
  {
    return DataType< ::motion_planning_kuka::SrvRobotCommand >::value();
  }
  static const char* value(const ::motion_planning_kuka::SrvRobotCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_PLANNING_KUKA_MESSAGE_SRVROBOTCOMMAND_H
